
services:
  frontend:
    image: node:slim
  api:
    image: python:3.13-slim
  mq:
  image: rabbitmq
  database:
    image: supabase
  cache:
    image: redis:latest
  orchestration:
    image: langchain/langchain
  vectordb:
    image: semitechnologies/weaviate:1.38.9-d2bb03f.amd64
  tesing:
    image: grafana/grafana-oss
  monitoring:
    image: prom/prometheus